repositories:
  - https://github.com/stanfordspezi/speziaccount
  - https://github.com/stanfordspezi/spezifirebase
  - https://github.com/stanfordspezi/spezionboarding
  - https://github.com/stanfordspezi/spezischeduler
  - https://github.com/stanfordspezi/spezistorage
  - https://github.com/stanfordspezi/speziviews
  - https://github.com/stanfordspezi/spezillm
  - https://github.com/stanfordspezi/spezihealthkit
  - https://github.com/stanfordspezi/spezitemplateapplication 