repositories:
  - title: Spezi Account
    url: https://github.com/stanfordspezi/speziaccount
    filename: speziaccount.md
  - title: Spezi Chat
    url: https://github.com/stanfordspezi/spezichat
    filename: spezichat.md
  - title: Spezi Contact
    url: https://github.com/stanfordspezi/spezicontact
    filename: spezicontact.md
  - title: Spezi Firebase
    url: https://github.com/stanfordspezi/spezifirebase
    filename: spezifirebase.md
  - title: Spezi Onboarding
    url: https://github.com/stanfordspezi/spezionboarding
    filename: spezionboarding.md
  - title: Spezi Scheduler
    url: https://github.com/stanfordspezi/spezischeduler
    filename: spezischeduler.md
  - title: Spezi Storage
    url: https://github.com/stanfordspezi/spezistorage
    filename: spezistorage.md
  - title: Spezi Views
    url: https://github.com/stanfordspezi/speziviews
    filename: speziviews.md
  - title: Spezi Access Guard
    url: https://github.com/stanfordspezi/speziaccessguard
    filename: speziaccessguard.md
  - title: Spezi Notifications
    url: https://github.com/stanfordspezi/spezinotifications
    filename: spezinotifications.md
  - title: Spezi LLM
    url: https://github.com/stanfordspezi/spezillm
    filename: spezillm.md
  - title: Spezi HealthKit
    url: https://github.com/stanfordspezi/spezihealthkit
    filename: spezihealthkit.md
  - title: Spezi Medication
    url: https://github.com/stanfordspezi/spezimedication
    filename: spezimedication.md
  - title: Spezi Template Application
    url: https://github.com/stanfordspezi/spezitemplateapplication
    filename: spezitemplateapplication.md 